import '../predefined_skill.dart';

const predefinedSystemSkill = PredefinedSkill(
  id: 'meow.system',
  title: 'Meow Agent system',
  summary:
      'Inspect and update agents, providers, profile, memory, tools, and configuration.',
  toolGroups: ['system'],
  toolNames: [
    'system.self',
    'system.rtb',
    'system.workspace.schema',
    'system.workspace.read',
    'system.profile.update',
    'system.memory.append',
    'system.memory.search',
    'system.config.read',
    'system.config.patch',
    'system.tools.list',
    'system.export_all',
    'system.import',
    'agent.create',
    'agent.delete',
    'agent.update',
    'agent.soul.read',
    'agent.list',
    'provider.create',
    'provider.delete',
    'provider.update',
    'provider.list',
    'sqlite.query',
  ],
  useWhen: [
    'The user asks about Meow Agent capabilities, tools, modules, agents, or providers.',
    'The user gives identity, profile, timezone, preferred language, or communication-style information.',
    'The user asks the agent to remember or search durable memory.',
    'The user asks about system database state that structured system tools cannot answer directly.',
    'Identity/profile data is managed through system.profile.update.',
    'Durable memory facts/preferences are managed through system.memory.append/search.',
    'Agent persona lives in agent_soul; read with agent.soul.read or system.config.read, update self with system.profile.update or another agent with agent.update.',
    'System database meow_core.db tables include agents, agent_soul, agent_memory, agent_events, providers, modules, agent_module_permissions, and app_settings.',
    'Use sqlite.query only for read-only system introspection that structured tools cannot answer.',
  ],
  avoidWhen: [
    'The user asks about user-defined custom tables; use meow.database.',
    'The user asks about workspace documents; use meow.files.',
    'Never store profile, memory, or persona data as files.',
    'Never use sqlite.query for user-defined tables; use meow.database instead.',
  ],
  requiredContextKeys: ['agent_identity', 'runtime_registry'],
  examples: [
    '"my name is <name>" -> system.profile.update.',
    '"remember I prefer short answers" -> system.memory.append.',
    '"what tools do you have?" -> system.tools.list.',
    '"what is <name>\'s persona?" -> agent.soul.read.',
    '"create a new agent named <name>" -> agent.create.',
    '"how many agents have empty persona?" -> sqlite.query only when structured tools cannot answer.',
  ],
  relatedSkillIds: ['meow.files'],
);
